
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gymapp_development
test:
  <<: *default
  database: gymapp_test

production:
  <<: *default
  database: gymapp_production
  username: gymapp_club
  password: <%= ENV['GYMAPP_DATABASE_PASSWORD'] %>
